[[pair]]
name = "XLM_BTC"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "BTC"
counter_asset_issuer = "GATEMHCCKCY67ZUCKTROYN24ZYT5GK4EQZ65JJLDHKHRUZI3EUEKMTCH"  #naobtc

[[pair]]
name = "XLM_BTC"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "BTC"
counter_asset_issuer = "GDXTJEK4JZNSTNQAWA53RZNS2GIKTDRPEUWDXELFMKU52XNECNVDVXDI" #vcbear

[[pair]]
name = "XLM_BTC"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "BTC"
counter_asset_issuer = "GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF" #apay.io

[[pair]]
name = "XLM_BTC"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "BTC"
counter_asset_issuer = "GBSTRH4QOTWNSVA6E4HFERETX4ZLSR3CIUBLK7AXYII277PFJC4BBYOG" #stronghold

[[pair]]
name = "XLM_CNY"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "CNY"
counter_asset_issuer = "GAREELUB43IRHWEASCFBLKHURCGMHE5IF6XSE7EXDLACYHGRHM43RFOX"

[[pair]]
name = "XLM_EUR"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "EURT"
counter_asset_issuer = "GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"

[[pair]]
name = "XLM_JPY"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "JPY"
counter_asset_issuer = "GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM"

[[pair]]
name = "XLM_PHP"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "PHP"
counter_asset_issuer = "GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"

[[pair]]
name = "EUR_PHP"
base_asset_code = "EURT"
base_asset_issuer = "GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"
counter_asset_code = "PHP"
counter_asset_issuer = "GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"

[[pair]]
name = "XLM_XRP"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "XRP"
counter_asset_issuer = "GA7FCCMTTSUIC37PODEL6EOOSPDRILP6OQI5FWCWDDVDBLJV72W6RINZ"


[[pair]]
name = "XLM_XEL"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "XEL"
counter_asset_issuer = "GAXELY4AOIRVONF7V25BUPDNKZYIVT6CWURG7R2I6NQU26IQSQODBVCS"  #naobtc

[[pair]]
name = "BTC_XEL"
base_asset_code = "BTC"
base_asset_issuer = "GATEMHCCKCY67ZUCKTROYN24ZYT5GK4EQZ65JJLDHKHRUZI3EUEKMTCH"
counter_asset_code = "XEL"
counter_asset_issuer = "GAXELY4AOIRVONF7V25BUPDNKZYIVT6CWURG7R2I6NQU26IQSQODBVCS"

[[pair]]
name = "XLM_ETH"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "ETH"
counter_asset_issuer = "GBSTRH4QOTWNSVA6E4HFERETX4ZLSR3CIUBLK7AXYII277PFJC4BBYOG" #stronghold

### Native Tokens

[[pair]]
name = "XLM_EQD"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "EQD"
counter_asset_issuer = "GCGEQJR3E5BVMQYSNCHPO6NPP3KOT4VVZHIOLSRSNLE2GFY7EWVSLLTN"

[[pair]]
name = "XLM_SLT"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "SLT"
counter_asset_issuer = "GCKA6K5PCQ6PNF5RQBF7PQDJWRHO6UOGFMRLK3DYHDOI244V47XKQ4GP"


###  APAY

[[pair]]
name = "XLM_ICN"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "ICN"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" # apay.io

[[pair]]
name = "XLM_BCH"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "BCH"
counter_asset_issuer = "GAEGOS7I6TYZSVHPSN76RSPIVL3SELATXZWLFO4DIAFYJF7MPAHFE7H4" # apay.io

[[pair]]
name = "XLM_LTC"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "LTC"
counter_asset_issuer = "GC5LOR3BK6KIOK7GKAUD5EGHQCMFOGHJTC7I3ELB66PTDFXORC2VM5LP" #apay.io

[[pair]]
name = "XLM_ETH"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "ETH"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" #apay.io

[[pair]]
name = "XLM_BAT"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "BAT"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" #apay.io

[[pair]]
name = "XLM_KIN"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "KIN"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" #apay.io

[[pair]]
name = "XLM_LINK"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "LINK"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" #apay.io

[[pair]]
name = "XLM_MTL"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "MTL"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" #apay.io

[[pair]]
name = "XLM_OMG"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "OMG"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" #apay.io

[[pair]]
name = "XLM_SALT"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "SALT"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" #apay.io

[[pair]]
name = "XLM_ZRX"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "ZRX"
counter_asset_issuer = "GBDEVU63Y6NTHJQQZIKVTC23NWLQVP3WJ2RI2OTSJTNYOIGICST6DUXR" #apay.io

[[pair]]
name = "XLM_MOBI"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "MOBI"
counter_asset_issuer = "GA6HCMBLTZS5VYYBCATRBRZ3BZJMAFUDKYYF6AH6MVCMGWMRDNSWJPIH" #mobi

[[pair]]
name = "XLM_HKD"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "HKDT"
counter_asset_issuer = "GABSZVZBYEO5F4V5LZKV7GR4SAJ5IKJGGOF43BIN42FNDUG7QPH6IMRQ" #cryptomover

[[pair]]
name = "XLM_RMT"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "RMT"
counter_asset_issuer = "GCVWTTPADC5YB5AYDKJCTUYSCJ7RKPGE4HT75NIZOUM4L7VRTS5EKLFN" #https://sureremit.co/

[[pair]]
name = "XLM_ABDT"
base_asset_code = "XLM"
base_asset_issuer = "native"
counter_asset_code = "ABDT"
counter_asset_issuer = "GDZURZR6RZKIQVOWZFWPVAUBMLLBQGXP2K5E5G7PEOV75IYPDFA36WK4" 



